"""rename department

Revision ID: 0b88f539d039
Revises: 49ec18b64417
Create Date: 2024-06-09 19:43:07.893201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b88f539d039'
down_revision = '49ec18b64417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
   


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
